[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

[lib]
name = "graphics"
path  = "src/lib.rs"

[dependencies]
tracing = "0.1"
vek = "0.15"
image = "0.24"
backtrace = "0.3"
glyph_brush = "0.7.5"
winit = "0.29"

[dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter"]

[dependencies.anyhow]
version = "1"
features = ["backtrace"]

[dependencies.wgpu]
version = "0.19"
features = ["spirv"]

[dependencies.shaderc]
version = "0.7"
optional = true

[dependencies.opentype437]
path = "../opentype437"
